server:
  port: 9001


# 项目相关配置
ht:
  # 名称
  name: ht
  # 版本
  version: 1.0
  # 验证码类型 math 数组计算 char 字符验证
  captchaType: math

spring:
  # redis 配置
  redis:
    # 地址
    host: 47.97.105.152
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    password: 123456
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
